version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper

    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  
  kafka:
      image: confluentinc/cp-kafka:latest
      hostname: kafka
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL_SAME_HOST://:29092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_NUM_PARTITIONS: 1

  producer:
    image: shiva0612/fable:latest
    container_name: producer
    command: ./producer  
    ports:
      - 8080:8080
    depends_on:
      - kafka 
    volumes:
      - /Users/kamarapushivachandra/Desktop/coding/fable/producer/producer.json:/app/producer.json
  
  consumer:
    image: shiva0612/fable:latest
    container_name: consumer 
    command: ./consumer
    depends_on:
      - zookeeper
      - kafka
      - producer
      - postgres
    volumes:
      - /Users/kamarapushivachandra/Desktop/coding/fable/consumer/consumer.json:/app/consumer.json
    
  http_test:
    image: shiva0612/fable:latest
    container_name: http_tester
    command: ./http_tester --host producer
    depends_on:
      - producer
      - consumer 
    
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=shiva
      - POSTGRES_PASSWORD=0612
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


